version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  shellcheck: circleci/shellcheck@3.1.1

jobs:
  init:
    docker:
      - image: python:3.7.9-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - shellcheck/install
      # - run:
      #     command: shellcheck <options>
      #     name: Run Shellcheck command
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .capstone-project
            source .capstone-project/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            make install
      - save_cache:
          paths:
            - ./.capstone-project # TODO: Include in cache the "bin" directory
          key: v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .capstone-project/bin/activate
            make lint
  build-and-push-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            pwd
            # cd frontend
            # docker build -t $DOCKER_LOGIN/hello-app .
            # docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            # docker push $DOCKER_LOGIN/hello-app
workflows:
  default:
    jobs:
      - init
      - build-and-push-docker-image:
          requires: [init]
      # - docker/publish:
      #     matrix:
      #       parameters:
      #         image: [$DOCKER_LOGIN/hello-app]
      #         path: [hello_app]
      #         docker-context: [hello_app]
      #         deploy: [true]
      #         # We publish two images with different version tags:
      #         # - numbered version
      #         # - "latest"
      #         # tag: ['$(<hello_app/VERSION.txt)-${CIRCLE_SHA1:0:7}', 'latest']
      #         tag: ["$(<hello_app/VERSION.txt)", "latest"]
      #         update-description: [true]
      # requires: [init]
